baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hacking to the Gate'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'kawingt2'               
  github = 'louiskwt'                 
  rss = true                                # show rss icon
